development:
  adapter: postgresql
  encoding: unicode
  database: jerry
  host: localhost
  pool: 5
  username: tom
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: localhost
  pool: 20
  username: vysakh
  password: 1234@abcd
